/**
 * Generates an asset manifest for embedding frontend assets in the Bun binary.
 * This script scans dist/client and creates a TypeScript module that exports
 * functions to serve each asset.
 */

import { readdir, readFile, writeFile, stat } from "fs/promises";
import path from "path";

const DIST_CLIENT = path.resolve(import.meta.dirname, "../dist/client");
const OUTPUT_FILE = path.resolve(
  import.meta.dirname,
  "../src/server/assets/embedded.ts"
);

interface AssetEntry {
  path: string;
  relativePath: string;
  mimeType: string;
}

function getMimeType(filePath: string): string {
  const ext = path.extname(filePath).toLowerCase();
  const mimeTypes: Record<string, string> = {
    ".html": "text/html",
    ".css": "text/css",
    ".js": "application/javascript",
    ".json": "application/json",
    ".png": "image/png",
    ".jpg": "image/jpeg",
    ".jpeg": "image/jpeg",
    ".gif": "image/gif",
    ".svg": "image/svg+xml",
    ".ico": "image/x-icon",
    ".woff": "font/woff",
    ".woff2": "font/woff2",
    ".ttf": "font/ttf",
    ".eot": "application/vnd.ms-fontobject",
  };
  return mimeTypes[ext] ?? "application/octet-stream";
}

async function* walkDir(dir: string): AsyncGenerator<string> {
  const entries = await readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      yield* walkDir(fullPath);
    } else if (entry.isFile()) {
      yield fullPath;
    }
  }
}

async function collectAssets(): Promise<AssetEntry[]> {
  const assets: AssetEntry[] = [];

  for await (const filePath of walkDir(DIST_CLIENT)) {
    const relativePath = path.relative(DIST_CLIENT, filePath);
    // Normalize to URL path format
    const urlPath = "/" + relativePath.split(path.sep).join("/");
    assets.push({
      path: filePath,
      relativePath: urlPath,
      mimeType: getMimeType(filePath),
    });
  }

  return assets;
}

async function generateModule(assets: AssetEntry[]): Promise<string> {
  const lines: string[] = [
    "// AUTO-GENERATED FILE - DO NOT EDIT",
    "// Generated by scripts/generate-assets.ts",
    "",
    "/**",
    " * Embedded frontend assets for production builds.",
    " * Files are imported using the { type: \"file\" } attribute so Bun embeds",
    " * them in the compiled binary and provides usable paths at runtime.",
    " */",
    "",
  ];

  // Generate import statements with { type: "file" } attribute
  for (let i = 0; i < assets.length; i++) {
    const asset = assets[i]!;
    const filePath = asset.relativePath.slice(1); // Remove leading /
    // Path: src/server/assets/ -> ../../.. -> project root -> dist/client/
    lines.push(`import asset${i} from "../../../dist/client/${filePath}" with { type: "file" };`);
  }

  lines.push("");
  lines.push("interface EmbeddedAsset {");
  lines.push("  path: string;");
  lines.push("  mimeType: string;");
  lines.push("}");
  lines.push("");
  lines.push("const embeddedAssets: Record<string, EmbeddedAsset> = {");

  for (let i = 0; i < assets.length; i++) {
    const asset = assets[i]!;
    const escapedPath = asset.relativePath.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
    lines.push(`  "${escapedPath}": { path: asset${i}, mimeType: "${asset.mimeType}" },`);
  }

  lines.push("};");
  lines.push("");
  lines.push("interface EmbeddedAssetResult {");
  lines.push("  file: () => ReturnType<typeof Bun.file>;");
  lines.push("  mimeType: string;");
  lines.push("}");
  lines.push("");
  lines.push("export function getEmbeddedAsset(urlPath: string): EmbeddedAssetResult | undefined {");
  lines.push("  const asset = embeddedAssets[urlPath];");
  lines.push("  if (!asset) return undefined;");
  lines.push("  return {");
  lines.push("    file: () => Bun.file(asset.path),");
  lines.push("    mimeType: asset.mimeType,");
  lines.push("  };");
  lines.push("}");
  lines.push("");

  return lines.join("\n");
}

async function main(): Promise<void> {
  // Check if dist/client exists
  try {
    await stat(DIST_CLIENT);
  } catch {
    console.error("Error: dist/client does not exist. Run 'pnpm run build:client' first.");
    process.exit(1);
  }

  console.log("Scanning dist/client for assets...");
  const assets = await collectAssets();
  console.log(`Found ${assets.length} assets`);

  const moduleContent = await generateModule(assets);

  // Ensure output directory exists
  const outputDir = path.dirname(OUTPUT_FILE);
  await Bun.write(path.join(outputDir, ".gitkeep"), "");

  await writeFile(OUTPUT_FILE, moduleContent, "utf-8");
  console.log(`Generated ${OUTPUT_FILE}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
